version: '3.9'

networks:
  walletnet:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    networks:
      - walletnet
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: wallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  walletapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: walletapi
    networks:
      - walletnet
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: walletuser
      SPRING_DATASOURCE_PASSWORD: wallet
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: /api
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - walletnet
    ports:
      - "80:80"
    depends_on:
      - walletapi
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
